apiVersion: v1
kind: Service
metadata:
  name: dev-prestashop-service
  labels:
    app: dev-prestashop
spec:
  type: NodePort
  selector:
    app: dev-prestashop
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30083