apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-wordpress-deployment
  labels:
    app: dev-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-wordpress
  template:
    metadata:
      labels:
        app: dev-wordpress
    spec:
      containers:
        - name: dev-wordpress
          image: wordpress:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "dev-mysql.default.svc.cluster.local"
            - name: WORDPRESS_DB_USER
              value: "root"
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-mysql-secret
                  key: MYSQL_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: dev-mysql-secret
                  key: MYSQL_DATABASE
            - name: WORDPRESS_DEBUG
              value: "1"
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('WP_DEBUG', true);
                define('WP_DEBUG_LOG', true);
                define('WP_DEBUG_DISPLAY', false);
                define('FS_METHOD', 'direct');
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html/wordpress
      volumes:
        - name: wordpress-data
          hostPath:
            path: /mnt/data/wordpress