apiVersion: v1
kind: Service
metadata:
  name: dev-wordpress-service
  labels:
    app: dev-wordpress
spec:
  type: NodePort
  selector:
    app: dev-wordpress
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081