apiVersion: v1
kind: Service
metadata:
  name: dev-mysql
  labels:
    app: dev-mysql
spec:
  clusterIP: None
  selector:
    app: dev-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306