apiVersion: v1
kind: Secret
metadata:
  name: dev-mysql-secret
type: Opaque
stringData:
  DB_HOST: "dev-mysql"
  MYSQL_ROOT_PASSWORD: "test"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "test"
  MYSQL_DATABASE: "wordpress"