apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: dev.local
      http:
        paths:
          # - path: /phpmyadmin(/|$)(.*)
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: dev-phpmyadmin
          #       port:
          #         number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: dev-stack-local
                port:
                  number: 80