apiVersion: v1
kind: Service
metadata:
  name: dev-phpmyadmin-service
  labels:
    app: dev-phpmyadmin
spec:
  type: NodePort
  selector:
    app: dev-phpmyadmin
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30082