services:
  mysql-joomla:
    image: mysql:8.0
    restart: always
    container_name: mysql-joomla
    ports: 
      - "3309:3306"
    command: --default-authentication-plugin=mysql_native_password  --explicit_defaults_for_timestamp=1
    #command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: joomla
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
        #MYSQL_USER: root
    volumes:
      - ../../mysql/init-joomla.sql:/docker-entrypoint-initdb.d/init-joomla.sql
      - mysql_joomla_data:/var/lib/mysql
    networks:
      - local-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ptest"]
      interval: 10s
      timeout: 5s
      retries: 10

  joomla:
    container_name: joomla
    #image: joomla:5.4.1
    #image: joomla:3.9.27
    build:
      context: .
      dockerfile: DockerfileJoomla
    restart: unless-stopped
    depends_on:
      mysql-joomla:
      condition: service_healthy
    ports:
      - 84:80
    environment:
      JOOMLA_DB_HOST: mysql-joomla
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: test
    networks:
      - local-network
    volumes:
      - ../../www/joomla:/var/www/html

  ngrok-joomla:
      image: ngrok/ngrok:latest
      container_name: ngrok-joomla
      restart: always
      depends_on:
          - joomla
      environment:
          # Set NGROK_AUTHTOKEN in your shell or in a .env file
          #NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN:-}"
          NGROK_AUTHTOKEN: "1sOeDncqDzLcjK5FomCsS130TGu_3v67ByFwBgSSJdgicEPQd"
      command: ["http", "joomla:80"]
      ports:
        - "4044:4040" # ngrok web UI
      networks:
        - local-network

volumes:
  mysql_joomla_data: {}

networks:
  local-network: